export const icon = ({ className }: { className?: string }) => (
    <svg
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className={className}
    >
        <circle
            cx="6.5"
            cy="6.5"
            r="3.5"
            stroke="currentColor"
            strokeWidth="1.5"
        />
        <circle
            cx="6.5"
            cy="17.5"
            r="3.5"
            stroke="currentColor"
            strokeWidth="1.5"
        />
        <circle
            cx="17.5"
            cy="6.5"
            r="3.5"
            stroke="currentColor"
            strokeWidth="1.5"
        />
        <circle
            cx="17.5"
            cy="17.5"
            r="3.5"
            stroke="currentColor"
            strokeWidth="1.5"
        />
    </svg>
);
