export const icon = ({ className }: { className?: string }) => (
    <svg
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className={className}
    >
        <circle
            cx="7"
            cy="12"
            r="0.75"
            stroke="currentColor"
            strokeWidth="1.5"
        />
        <circle
            cx="12"
            cy="12"
            r="0.75"
            stroke="currentColor"
            strokeWidth="1.5"
        />
        <circle
            cx="17"
            cy="12"
            r="0.75"
            stroke="currentColor"
            strokeWidth="1.5"
        />
        <rect
            x="2"
            y="8"
            width="20"
            height="8"
            rx="3"
            stroke="currentColor"
            strokeWidth="1.5"
        />
    </svg>
);
