name: Build Search Index
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Search Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: cd .dev && npm install

      - run: cd .dev && npm run build:search-index
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          NEXT_PUBLIC_DOCSEARCH_APP_ID: ${{ secrets.NEXT_PUBLIC_DOCSEARCH_APP_ID }}

      - name: Build Chat Index
        env:
          TOKEN: ${{ secrets.CHAT_TOKEN }}
        run: |
          echo sleeping a bit to wait for index...
          sleep 5
          curl https://ai.glide.party/api/chat-index
